# -*- coding: utf-8 -*-
"""centenarios_metabolomica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHMrsxJHnW2pY9KvWdn6LNFeQrmNXDVx
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

def load_file(path):
  return pd.read_excel(path)

path = '/content/drive/MyDrive/centenarios metabolomica/centenarios_metabolomica.xlsx'
df = load_file(path)

df.keys()

# Drop duplicated and empty rows
df = df.reset_index(drop=True)
rows_to_drop = [7, 17, 33, 123]
df = df.drop(index = rows_to_drop)

df

print("Shape:", df.shape)
print(f"Dataset dimensions → {df.shape[0]} individuals × {df.shape[1]} variables")

patterns_to_drop = [
    'Lymphocytes',
    'B cells',
    'T cells',
    'CD3',
    'CD4',
    'CD8',
    'TEMRA',
    'NAIVE',
    'EM ',
    'CM ',
    'KLRG1',
    'CD27',
    'CD28',
    'CD95',
    'CD57'
]

immune_cols = [
    col for col in df.columns
    if any(pat in col for pat in patterns_to_drop)
]

print(f"Columns to drop: {len(immune_cols)}")

df = df.drop(columns=immune_cols)
print(f"Dataset dimensions → {df.shape[0]} individuals × {df.shape[1]} variables")

dtype_summary = (
    df.dtypes
    .value_counts()
    .reset_index()
    .rename(columns={'index': 'dtype', 0: 'number_of_variables'})
)

dtype_summary

variable_counts = pd.DataFrame({
    'variable_name': df.columns,
    'non_null_count': df.notna().sum(),
    'missing_count': df.isna().sum(),
    'non_null_pct': df.notna().mean() * 100
}).sort_values('non_null_count', ascending=False)

variable_counts

dicc_path = "/content/drive/MyDrive/centenarios metabolomica/centenarios_diccionario.xlsx"

dicc_df = pd.read_excel(dicc_path, sheet_name="Diccionario")

dicc_keys = dicc_df['Variable'].dropna().astype(str)

"""# Variables que se encuentran tanto en el diccionario como en el dataset

"""

data_keys = variable_counts['variable_name']
common_keys = (set(dicc_keys) & set(data_keys))
print(common_keys)
print(len(common_keys))

"""# Variables que están en el diccionario pero no en el dataset"""

dicc_only = set(dicc_keys) - set(data_keys)
print(dicc_only)
print(len(dicc_only))

"""# Variables que están en el dataset pero no en el diccionario


"""

data_only = set(data_keys) - set(dicc_keys)
print(data_only)
print(len(data_only))

set_a = list(data_keys)
set_b = list(dicc_keys)


df.describe()

numerical_cols = df.select_dtypes(include=['float64']).columns.tolist()
numerical_pun = df.select_dtypes(include=['int64']).columns.tolist()
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

print(f"Number of numerical columns: {len(numerical_cols)}")
print(f"Number of numerical (with categories) columns: {len(numerical_cols)}")
print(f"Number of categorical columns: {len(categorical_cols)}")

"""**Reasoning**:
Now that the numerical and categorical columns have been identified and stored in their respective lists, the next step is to display these lists as requested by the subtask.


"""

print("Numerical Columns:")
print(numerical_cols)
print("\nCategorical Columns:")
print(categorical_cols)

lista_numericas = list(df[numerical_cols])
lista_numericas_categoria = list(df[numerical_pun])
lista_categoricas = list(df[categorical_cols])

with open("lista_numericas.txt", "w", encoding="utf-8") as f:
    for col in lista_numericas:
        f.write(f"{col}\n")

with open("lista_categoricas.txt", "w", encoding="utf-8") as f:
    for col in lista_categoricas:
        f.write(f"{col}\n")

with open("lista_numericas_cat.txt", "w", encoding="utf-8") as f:
    for col in lista_categoricas:
        f.write(f"{col}\n")